# BungeeGuard Configuration

# Allowed authentication tokens.
allowed-tokens:
  - "YOUR_TOKEN"

# Messages

# Kick message sent to connections without any forwarded data from the proxy.
# Most likely a vanilla client connecting directly to the server, bypassing the proxy.
no-data-kick-message:
  - '&cFollow the step by step of installing nLogin on Bungeecord:'
  - '&bhttps://www.nickuc.com/docs/bungeeguard'
  - ''
  - '&cIn case of problems, contact our support: &bhttps://www.nickuc.com/discord'

# Kick message sent to connections with forwarding data, but without a correct BungeeGuard token
# included in their handshake. Assuming BungeeGuard is installed correctly on all proxies,
# this is most likely a client trying to exploit the BungeeCord protocol to spoof their uuid.
invalid-token-kick-message:
  - '&cSorry, but an invalid authentication code has been provided.'
  - ''
  - '&cMake sure that you configured using the same token as the Bungeecord.'
